--- Unclassified globals
-- Various variables/functions with no specific, to override _fallback functions,
-- comptability reason, such as other theme specific function, or Anomaly-Only stuffs.
-- @module AnomalyGlobals